FROM python
RUN pip install flask
RUN pip install Faker
COPY Micro_Web.py /home/MicroWebFramework/Micro_Web.py
EXPOSE 8080
CMD python3 /home/MicroWebFramework/Micro_Web.py
FROM python
RUN pip install flask
RUN pip install Faker
COPY Micro_Web.py /home/MicroWebFramework/Micro_Web.py
EXPOSE 8080
CMD python3 /home/MicroWebFramework/Micro_Web.py
